database:
  url: postgresql+asyncpg://postgres:postgres@localhost:5432/test_db
  echo: true

redis:
  url: redis://localhost:6379/1

jwt:
  secret_key: test_secret_key
  algorithm: HS256
  access_token_expire_minutes: 30 