services:
  gateway:
    build: 
      context: .
      dockerfile: Dockerfile.gateway
    ports:
      - "8000:8000"
    environment:
      - GATEWAY_SERVICE_REGISTRY_URL=http://service-registry:8500
      - GATEWAY_SERVICE_REGISTRY_TOKEN=xxx
    depends_on:
      - service-registry
      - agent-service
      - plugin-service

  agent-service:
    build: .
    ports:
      - "8001:8001"
    environment:
      - SERVICE_NAME=agent
      - SERVICE_PORT=8001

  plugin-service:
    build: .
    ports:
      - "8002:8002"
    environment:
      - SERVICE_NAME=plugin
      - SERVICE_PORT=8002 